/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessInfo = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'aboutText' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Int,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateBusinessInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessInfo = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'aboutText' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Int,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBusinessInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };